[package]
name = "vxectl"
version = "0.1.0"
edition = "2021"
description = "Control your VXE gaming mouse from the command line"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5", features = ["derive"] }
colored = "3.1.1"
hidapi = "2.6"
thiserror = "2.0"
